// Root
export const UPDATE_WELCOME_STATE = 'UPDATE_WELCOME_STATE'

// About

// Transition
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const UPDATE_SLIDE_DIRECTION = 'UPDATE_SLIDE_DIRECTION'
export const UPDATE_TRANSITION_STATE = 'UPDATE_TRANSITION_STATE'
